FROM postgis/postgis:14-3.2

RUN apt-get update && \
    apt-get install -y curl unzip postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY init_analytics_db.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init_analytics_db.sh
